 set nocompatible               " be iMproved
 filetype off                   " required!

" Set temporary directory (don't litter local dir with swp/tmp files)
set directory=~/tmp/vim_temp

set hidden

"Use case-smart searching
set ignorecase
set smartcase

set title
set scrolloff=3
set shortmess=atI

let mapleader = ","

 set rtp+=~/.vim/bundle/vundle/
 call vundle#rc()

 " let Vundle manage Vundle
 " required! 
 Bundle 'gmarik/vundle'

Bundle 'godlygeek/csapprox'
Bundle 'altercation/vim-colors-solarized'
Bundle 'pangloss/vim-javascript'
Bundle 'bitfyre/vim-indent-html'
Bundle 'thisivan/vim-bufexplorer'
Bundle 'tsaleh/vim-matchit'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'vim-json-bundle'
Bundle 'tpope/vim-markdown'
Bundle 'duff/vim-scratch'
Bundle 'tpope/vim-surround'
Bundle 'kana/vim-textobj-user'
Bundle 'nelstrom/vim-textobj-rubyblock'
Bundle 'vim-scripts/vim-json-bundle'

" NERDTree CONFIGURATION

" Enable nice colors
let NERDChristmasTree = 1

" Make it easy to see where we are
let NERDTreeHighlightCursorline = 1

" Make bookmarks visible
let NERDTreeShowBookmarks = 1

" Show hidden files
let NERDTreeShowHidden = 1

" Don't hijack NETRW
let NERDTreeHijackNetrw = 0
let NERDTreeIgnore=['\.$', '\~$']

" Make F2 open NERDTree
nmap <F2> :NERDTreeToggle<CR>

" Color
if has('syntax')
  syntax on
  set term=screen-256color
  set background=dark
  colorscheme solarized
endif

" html indentation provided by Andy Wokula is faster. But you need to make some configuration.
" Suggested configuration:
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"
